import {
  bgBlack,
  bgBlackBright,
  bgBlue,
  bgBlueBright,
  bgCyan,
  bgCyanBright,
  bgGreen,
  bgGreenBright,
  bgMagenta,
  bgMagentaBright,
  bgRed,
  bgRedBright,
  bgWhite,
  bgWhiteBright,
  bgYellow,
  bgYellowBright,
  black,
  blue,
  blueBright,
  bold,
  CSPair,
  cyan,
  cyanBright,
  dim,
  gray,
  green,
  greenBright,
  grey,
  hidden,
  inverse,
  italic,
  magenta,
  magentaBright,
  red,
  redBright,
  reset,
  strikethrough,
  underline,
  white,
  whiteBright,
  yellow,
  yellowBright
} from 'ansi-styles';

const isAnsiFactory = (codePair: CSPair): ((text: string) => boolean) => {
  const styleBegin = codePair.open,
        styleEnd = codePair.close;

  return function (text: string): boolean {
    const positionBegin = text.indexOf(styleBegin),
          positionEnd = text.indexOf(styleEnd);

    return (positionBegin !== -1) && (positionEnd !== -1) && (positionBegin < positionEnd);
  };
};

const isAnsi = {
  reset: isAnsiFactory(reset),
  bold: isAnsiFactory(bold),
  dim: isAnsiFactory(dim),
  italic: isAnsiFactory(italic),
  underline: isAnsiFactory(underline),
  inverse: isAnsiFactory(inverse),
  hidden: isAnsiFactory(hidden),
  strikethrough: isAnsiFactory(strikethrough),
  black: isAnsiFactory(black),
  red: isAnsiFactory(red),
  green: isAnsiFactory(green),
  yellow: isAnsiFactory(yellow),
  blue: isAnsiFactory(blue),
  magenta: isAnsiFactory(magenta),
  cyan: isAnsiFactory(cyan),
  white: isAnsiFactory(white),
  gray: isAnsiFactory(gray),
  grey: isAnsiFactory(grey),
  redBright: isAnsiFactory(redBright),
  greenBright: isAnsiFactory(greenBright),
  yellowBright: isAnsiFactory(yellowBright),
  blueBright: isAnsiFactory(blueBright),
  magentaBright: isAnsiFactory(magentaBright),
  cyanBright: isAnsiFactory(cyanBright),
  whiteBright: isAnsiFactory(whiteBright),
  bgBlack: isAnsiFactory(bgBlack),
  bgRed: isAnsiFactory(bgRed),
  bgGreen: isAnsiFactory(bgGreen),
  bgYellow: isAnsiFactory(bgYellow),
  bgBlue: isAnsiFactory(bgBlue),
  bgMagenta: isAnsiFactory(bgMagenta),
  bgCyan: isAnsiFactory(bgCyan),
  bgWhite: isAnsiFactory(bgWhite),
  bgBlackBright: isAnsiFactory(bgBlackBright),
  bgRedBright: isAnsiFactory(bgRedBright),
  bgGreenBright: isAnsiFactory(bgGreenBright),
  bgYellowBright: isAnsiFactory(bgYellowBright),
  bgBlueBright: isAnsiFactory(bgBlueBright),
  bgMagentaBright: isAnsiFactory(bgMagentaBright),
  bgCyanBright: isAnsiFactory(bgCyanBright),
  bgWhiteBright: isAnsiFactory(bgWhiteBright)
};

export default isAnsi;
